### ISSUE TITLE
SUBTLE - using the alt attribute

### ISSUE THREAD

**Issue by Emik234** [ckimball875/prj-rev-bwfs-dasmoto#3]
You should consider adding an alt attribute to the images, that way if any of the images don't load for some reason, you don't get the broken link icon, rather the text you specify in alt will be displayed, more info here: https://www.w3schools.com/tags/att_img_alt.asp

**Comment by ckimball875** [comment]
I had not thought of that, but now that you mention it, I think I remember seeing that in an earlier section of this class somewhere.  Thanks!
